version: '2'
services:
  kafka:
    image: spotify/kafka:latest
    ports:
    - 2181:2181
    - 9092:9092
    environment:
    - ADVERTISED_PORT=9092
    - ADVERTISED_HOST=10.200.10.1
  legacyorderprocessor:
    build: ../my-legacy-order-processor
    ports:
    - 8086:8086
    depends_on:
    - kafka
    environment:
    - ENVIRONMENT=compose
  order:
    build: .
    ports:
    - 8085:8085
    depends_on:
    - kafka
    environment:
    - ENVIRONMENT=compose
